docker-compose-yaml: docker-compose.yml

project: midcamp-ep

tasks:
  pre-rollout:
    - run:
        name: drush sql-dump
        # Takes a pre-rollout backup of production sites only.
        command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
        service: cli
        when: LAGOON_ENVIRONMENT_TYPE=="production"

  post-rollout:
    - run:
        name: IF no Drupal installed & Pullrequest = Sync database from dev
        command: |
          if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
              drush -y sql-sync @lagoon.midcamp-ep-main @self
          fi
        service: cli
    - run:
        name: drush deploy
        # This will only run if the database exists.
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush deploy; fi
        service: cli
        shell: bash

environments:
  dev:
    routes:
      - nginx:
        - "dev.midcamp.org":
            tls-acme: 'true'
            insecure: Redirect
  main:
    routes:
      - nginx:
        - "midcamp.org":
            tls-acme: 'true'
            insecure: Redirect
        - "www.midcamp.org":
            tls-acme: 'true'
            insecure: Redirect
    cronjobs:
      - name: drush hourly cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
