docker-compose-yaml: docker-compose.yml

project: midcamp-ep

tasks:
  pre-rollout:
  # - run:
  #     name: drush sql-dump
  #     # Takes a pre-rollout backup of production sites only.
  #     command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
  #     service: cli
  #     when: LAGOON_ENVIRONMENT_TYPE=="production"

  post-rollout:
    - run:
        name: drush deploy
        # This will only run if the database exists.
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush deploy; fi
        service: cli
        shell: bash

environments:
  main:
    routes:
      - nginx:
        - "midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
        - "www.midcamp.org":
            tls-acme: 'false'
            insecure: Redirect
    cronjobs:
      - name: drush hourly cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
